# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Lenovo\Documents\untitled\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    cpath =""
    def setupUi(self, MainGUIFile):
        MainGUIFile.setObjectName("MainGUIFile")
        MainGUIFile.resize(1100, 750)
        MainGUIFile.setStyleSheet("background-color: rgb(33,33,33);")
        self.label = QtWidgets.QLabel(MainGUIFile)
        self.label.setGeometry(QtCore.QRect(0, 0, 1101, 751))
        self.label.setStyleSheet("border-image: url(D:/Hackthon/gallary/minebg.jpg);\n"
"border: 0px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainGUIFile)
        self.label_2.setGeometry(QtCore.QRect(330, 10, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Small Semibold")
        font.setPointSize(27)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-image: url(D:/Hackthon/gallary/minebot.png);\n"
"background-color: transparent;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(MainGUIFile)
        self.label_3.setGeometry(QtCore.QRect(330, 50, 401, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: transparent;\n"
"border-image: url(D:/Hackthon/gallary/tagline.png);")
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(MainGUIFile)
        self.frame.setGeometry(QtCore.QRect(-40, 110, 1221, 791))
        self.frame.setStyleSheet("background-color: transparent;\n"
"border : 0px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(300, 560, 541, 52))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgba(23,45,73,200);\n"
"border: 2px solid rgba(53,186,246,1);\n"
"border-radius:25px;\n"
"color:white;\n"
"padding-left:20px")
        self.lineEdit.setObjectName("lineEdit")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(240, 20, 701, 521))
        self.plainTextEdit.setStyleSheet("\n"
"")
        self.plainTextEdit.setStyleSheet("color: white")
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(900, 580, 41, 21))
        self.pushButton_2.setStyleSheet("background-color: transparent;\n"
"border-image: url(D:/Hackthon/gallary/enter.png);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(860, 570, 21, 31))
        self.pushButton.setStyleSheet("border-image: url(D:/Hackthon/gallary/mainmike.png);\n"
"background-color: transparent;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(240, 560, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("color: rgb(53,186,246);\n"
"\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(220, 0, 741, 631))
        self.label_5.setStyleSheet("background-color:rgba(53,186,246, 30);\n"
"border: 2px solid rgba(53,186,246,0.7);\n"
"border-radius: 25px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.plainTextEdit.raise_()
        self.pushButton_2.raise_()
        self.pushButton.raise_()
        self.lineEdit.raise_()
        self.comboBox.raise_()
        self.label_4 = QtWidgets.QLabel(MainGUIFile)
        self.label_4.setGeometry(QtCore.QRect(25, 15, 60, 60))
        self.label_4.setStyleSheet("background-color: transparent;\n"
"border-image: url(D:/Hackthon/gallary/logo.png);")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(MainGUIFile)
        self.label_6.setGeometry(QtCore.QRect(920, 5, 150, 80))
        self.label_6.setStyleSheet("border-image: url(D:/Hackthon/gallary/aiavengerslogo.png);\n" "background-color:transparent")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")

        self.retranslateUi(MainGUIFile)
        QtCore.QMetaObject.connectSlotsByName(MainGUIFile)

    def retranslateUi(self, MainGUIFile):
        _translate = QtCore.QCoreApplication.translate
        MainGUIFile.setWindowTitle(_translate("MainGUIFile", "MinesBot"))
        self.label_2.setText(_translate("MainGUIFile", " "))
        self.label_3.setText(_translate("MainGUIFile", " "))
        # self.lineEdit.setText(_translate("MainGUIFile", "    Enter your commands here"))
        self.pushButton_2.setText(_translate("MainGUIFile", " "))
        self.pushButton.setText(_translate("MainGUIFile", " "))
        self.comboBox.setItemText(0, _translate("MainGUIFile", "ENGLISH"))
        self.comboBox.setItemText(1, _translate("MainGUIFile", "HINDI"))
        self.comboBox.setItemText(2, _translate("MainGUIFile", "MARATHI"))
        self.label_4.setText(_translate("MainGUIFile", " "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainGUIFile = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(MainGUIFile)
    MainGUIFile.show()
    sys.exit(app.exec_())
